\mainmatter

# 表について

```{r, echo=FALSE}
rm(list=ls())
library(knitr)
# out_type <- opts_knit$get("rmarkdown.pandoc.to")
opts_chunk$set(warning=FALSE, message =FALSE)
```

データ `cars` を用いて回帰分析\index{かいきぶんせき@回帰分析}を実行する. 
```{r}
fm0<-lm(dist~speed, data=cars) 
fm1<-lm(dist~speed + I(speed^2), data=cars) 
```

結果は表 \@ref(tab:kable) のとおりである.
```{r kable, results="asis"}
if (!require(broom)){
  install.packages("broom", repos='http://cran.us.r-project.org')
  }
library(broom)
knitr::kable(tidy(summary(fm0)), booktabs = TRUE,
  caption = '単回帰分析の結果'
)
```



`texreg` の結果は表 \@ref(tab:texreg) のとおりである.

```{r, results='asis',message=FALSE}
if (!require(texreg)){
  install.packages("texreg", repos='http://cran.us.r-project.org')
  }
library(texreg)
bookdown_texreg <- function(lists,names,caption,label) {
  if (knitr:::is_latex_output()) {
    texreg(lists, caption=caption,label=label,
           custom.coef.names = names,
          caption.above=TRUE)
    } else {
    html_caption <- paste0("(#",label,"): ",caption)
    htmlreg(lists, caption=html_caption,
            custom.coef.names = names,
            doctype=FALSE,caption.above=TRUE)
  }
}
lists <- list(fm0, fm1)
names <- c("速度", "速度の自乗","定数項")
caption <- "texreg"
label <- "tab:texreg"
bookdown_texreg(lists,names,caption,label)
```

\begin{equation}
y_t=\alpha + \beta x_t + u_t (\#eq:1)
\end{equation}

数式 \@ref(eq:1) である. このソースコードは以下である.

```
\begin{equation}
y_t=\alpha + \beta x_t + u_t (\#eq:1)
\end{equation}
```

`"(#eq:1)"` でなく `(\#eq:1)` となっていることに注意されたい.


