# 図について

```{r}
rm(list=ls())
library(knitr)
out_type <- opts_knit$get("rmarkdown.pandoc.to")
opts_chunk$set(warning=FALSE, message =FALSE)
library(extrafont)
loadfonts(quiet=TRUE)
```
グラフィクス全般については @murrell_r_2011 を参照されたい.[^1] 

[^1]: 初版であるが翻訳されている [@murrell_r_2009].

## 基本グラフィクス
日本語フォントとして `IPAexGothic` を指定して, 図 \@ref(fig:base) となる.

```{r base, fig.cap="基本グラフィクスの日本語付きの図"}
par(family="IPAexGothic")
curve(dnorm(x),xlim=c(-3,3),main="正規分布")
```

## lattice
パッケージ lattice\index{lattice} を用いても日本語対応が可能で, 図 \@ref(fig:lattice) となる. lattice については @sarkar_2012 および その翻訳書 @sarkar_2012 を参照されたい.

```{r lattice, fig.cap="latticeの日本語付きの図"}
if (!require(lattice)){
  install.packages("lattice")
}
library(lattice)
trellis.par.set(list(grid.pars = list(fontfamily = 'IPAexGothic')))
myPanel <- function(x, y, xPos, yPos, ...) {
   myLm <- lm(y ~ x)                   # Fit a linear regression line
   panel.abline(myLm, col = "red")     # Add the regression line
   panel.xyplot(x, y, ...)             # Draw the points
   params <- paste(c("切片:", "傾き:"), # Parameters
                   signif(coef(myLm), 3), collapse="\n")
   ltext(xPos, yPos, params, cex = .8) # Add text to plot
 }
 xyplot( mpg ~ wt | factor(cyl), data = mtcars, panel = myPanel, pch = 16,
   xPos = 4.5, yPos = 30)
```

## ggplot2 
パッケージ ggplot2\index{ggplot2} を用いても日本語対応が可能で, 図 \@ref(fig:ggplot2) となる.

ggplot2 については @wickham_ggplot2:_2016-1 を参照されたい.[^2] 

[^2]: 初版であるが翻訳されている [@wickham_2012].

```{r ggplot2, fig.cap="ggplot2の日本語付きの図"}
if (!require(ggplot2)){
  install.packages("ggplot2")
  }
library(ggplot2)
theme_set( theme_bw( base_family= "IPAexGothic"))
gg <- ggplot(mtcars,aes(x=wt,y=mpg)) + geom_point()
gg <- gg + ggtitle("車の重さと燃費の関係")
gg <- gg + xlab("重さ") + ylab("燃費")
gg
```

