--- 
title: "book_title"
author: "author_name"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: bxjsreport
classoption: ja=standard, xelatex, base=12pt
# geometry: no
# monofont: "Source Code P  ro Light"
bibliography: template.bib
biblio-style: jeconunicode
link-citations: yes
lang: ja-JP
# github-repo: (your-github-repository)
# description: "This is a description. Please wrote a abstract this contents. "
---

# はじめに {-}

これは https://github.com/kazutan/bookdown_ja_template/ をフォークしたものです.
私が改変した文章の句点は半角ピリオドになっております.

違いは以下です:

+ lualatex でなく (宗教的理由で) xelatex にしている.
+ IPA font でなく IPAex font にしている
+ bxjsbook を使用していている
+ 日本語付きの図表の例を示している.
+ 日本語の索引と参考文献の例を示している.


以下は説明用の文章を貼り付けてます。**実際には削除してください**。

不明な点があれば, もしくはこのリポジトリのissue までおねがいします。

## 書籍ファイルの作成方法

### 必要なパッケージ,環境など
Knitr, rmarkdown, bookdownのパッケージがデータのレンダリングに必要です。またpandocの新しいのが必要で, 面倒でしたらRStudioの最新版をインストールしてください (内包してます)。

ggplot2逆引き記事内にて使用するパッケージも必要となります。おそらくggplot2パッケージぐらいで大丈夫だと思いますが, 面倒でしたらtidyverseパッケージを導入してください。これをインストールするとHadleyverseなパッケージ群が自動的にインストールされます。

オリジナルと違い, pdf book を日本語できちんとpdf book を作りたいので, マシンにtex環境が不可欠です.
色々なtex環境がありますが texlive が最適です.
2016 以降でないとスタイルファイル **bxjsbook** やユニコードに対応した索引作成ソフト **upmendex**  が使えません.

bookdown で pdf book を作成する際, デフォルトでは パッケージ `tinytex` 経由でコンパイルします.
そのさい, どうしても `bibtex` で参考文献リストを作成しています.
それを避けるために, 実行前に
```
options(tinytex.latexmk.emulation = FALSE)
```
を入力します. そうしてtexlive に付属する  **latexmk** を用いて
参考文献や索引を作成します.

設定ファイル `.latexmkrc` をホームディレクトリに置くだけだとうまくいかず,
プロジェクトフォルダ内にコピーしておく必要があります. わたしの設定ファイルは以下です:
```
$latex  = 'uplatex -kanji=utf8 -synctex=1';
$bibtex = 'upbibtex -kanji-internal=uptex';
$dvipdf  = 'dvipdfmx %O -o %D %S';
$makeindex = 'upmendex %O -o %D %S';
$pdf_previewer = 'open -a /Applications/Preview.app';
$pdf_mode = 3;                  #  3 = create pdf file by dvipdf
$pdf_update_method = 0;         #  0 =  auto update
```
`$latex` や `$dvipdf` は古いテフを使用している人とコミュニケートするための設定でここでは使っていません. また `$pdf_previewer` もここでは使いません.

bibtex のスタイルファイルは 

http://shirotakeda.org/ja/tex-ja/jecon-ja.html

にある `jecon.bst` のユニコード版 `jecon_unicode.bst` を使います.
ただ YAML がうまく  jecon_unicode.bst を読み込んでくれないので `jeconunicode.bst` にファイル名を変更しております. あと少しだけ修正しております.

日本語のフォントに埋め込み可能な IPAexフォントにしています. 
IPA フォントとの違いは欧米フォントがプロポーシャルになってることです. 以下からダウンロードしてください。

http://ipafont.ipa.go.jp/

日本語フォントを含めた各種のフォントを作図に用いると警告が出る場合があります.
警告無しで使用するために `extrafont` という
パッケージを用います. まず最初に
```
install.packages("extrafont")
extrafont::font_import(prompt=FALSE)
```
として読み込みます. 実際に使えるフォントは
```
extrafont::fonts()
```
で確認できます. セッションごとに
```
extrafont::loadfonts(quiet=TRUE)
```
を実行するとよいでしょう.

また, bookdown は utf-8 しか受け付けません。そのため windows ではうまく動かないかもしれません(未検証)。はやく mac か linux に移行しましょう.

私の作業環境 (動作確認環境) は, 最後にまとめて表示しています。

### Download

git clone して持ってくるか, 右側の Download Zip で持ってきてください:

```
$ git clone git@github.com:kenjimyzk/bookdown_ja-template.git
```

### レンダリング(本のファイル作成)

#### 種類

- gitbook形式: 以下のコードを実行
```
bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")
```
- epub形式: 以下のコードを実行
```
bookdown::render_book("index.Rmd", output_format = "bookdown::epub_book")
```
- pdf形式: 以下のコードを実行
```
options(tinytex.latexmk.emulation = FALSE)
bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")
```

RStudioを利用しているなら, BuildパネルでBuild Bookから選択してください。もしBuildタブがRStudioで表示されない場合,一度RStudioを終了させてもう一度開いてください。しかし `pdf_book` の生成はうまくいかないので注意されたい。

### 生成物の場所

生成物は,`docs`ディレクトリに置かれるように設定してます。`.epub`と`.pdf`は単独ファイルで,それ以外はgitbook形式のファイルとなります。

## session info
私の作業環境 (動作確認環境) です.
```{r}
sessionInfo()
```

## 今後やりたいこと
html の参考文献について日本語でのスタイルが上手く表記されていません.
jecon.bst のように和文文献と欧米文献を分類して, あいうえお順にしたいのですが, 現状ではできていません. csl について

+ http://docs.citationstyles.org/en/stable/specification.html
+ http://editor.citationstyles.org/visualEditor/
+ https://www.zotero.org/styles

あたりで勉強して作りたいと思います. 

